# Generated by Django 6.0.6 on 2026-06-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sluyg',
            new_name='slug',
        ),
    ]
